//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarea33
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public string Placa { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public string NombreCliente { get; set; }
        public string TelefonoCliente { get; set; }
        public string Tipo { get; set; }
        public string Categoria { get; set; }
    }
}
